/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ts.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Ts(props) {
  const { nodes, materials } = useGLTF("/ts.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={1.616}>
        <mesh
          geometry={nodes.Cube033.geometry}
          material={materials.Material}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          geometry={nodes.Curve.geometry}
          material={materials["Material.034"]}
          position={[0.272, -0.275, 0.121]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={6.014}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ts.glb");
