/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public_phone_booth.glb 
Author: BlayneIgnasiak (https://sketchfab.com/BlayneIgnasiak)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/public-phone-booth-3b50fb746d834312bce22c9fe3472726
Title: Public Phone Booth
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Phone(props) {
  const { nodes, materials } = useGLTF("/models/public_phone_booth.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_6.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_7.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_8.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_9.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_10.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_11.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_12.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_13.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_14.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_15.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_16.geometry}
            material={materials.UVgroup2}
          />
          <mesh
            geometry={nodes.defaultMaterial_17.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_18.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_19.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_20.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_21.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_22.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_23.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_24.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_25.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_26.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_27.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_28.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_29.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_30.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_31.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_32.geometry}
            material={materials.uvgroup1}
          />
          <mesh
            geometry={nodes.defaultMaterial_33.geometry}
            material={materials.uvgroup1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/public_phone_booth.glb");
